# Generated by Django 3.0.9 on 2020-08-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('about', models.TextField()),
                ('experience', models.BigIntegerField()),
                ('skills', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
