# Generated by Django 3.0.9 on 2020-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(max_length=120),
        ),
    ]
