# Generated by Django 3.0.9 on 2020-08-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200804_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_details', models.TextField()),
                ('no_of_quiz', models.BigIntegerField()),
                ('hrs_of_quiz', models.BigIntegerField()),
                ('no_of_video', models.BigIntegerField()),
                ('hrs_of_video', models.BigIntegerField()),
                ('no_of_music', models.BigIntegerField()),
                ('hrs_of_music', models.BigIntegerField()),
                ('no_of_images', models.BigIntegerField()),
                ('hrs_of_images', models.BigIntegerField()),
            ],
        ),
    ]
